# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1fe156bf7f30616fde4ba62c981e0c7d1ac152aa86e68b54bcad6b5d4cad51b79541abc599209b525d54d24cb16034bcaab5f38f1c63fe6a3fdad4ad2f3ceb7

test:
  secret_key_base: 0d26b012f72f9a887b7b3e465e303ca7c0a7f7392243a08e21ccf2795e6aad4a528d7c109d10e54231ca563b2f29392a65f47ee5a30a1398238a9bf07b1d0819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
